---
- name: configure pacman
  block:
    - lineinfile:
        path: /etc/pacman.conf
        regexp: '#Color'
        line: 'Color'
    - lineinfile:
        path: /etc/pacman.conf
        regexp: '#UseSyslog'
        line: 'UseSyslog'
    - lineinfile:
        path: /etc/pacman.conf
        regexp: '#TotalDownload'
        line: 'TotalDownload'
    - lineinfile:
        path: /etc/pacman.conf
        regexp: '#CheckSpace'
        line: 'CheckSpace'
    - lineinfile:
        path: /etc/pacman.conf
        regexp: '#ILoveCandy'
        line: 'ILoveCandy'
        insertafter: '# Misc options'

- name: Update lists and upgrade
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install reflector service
  copy:
    src: reflector.service
    dest: /etc/systemd/system/
  notify: enable reflector

- name: Install pacman hooks
  become: no
  aur:
    name:
      - kernel-modules-hook # keep kernel modules dir after an upgrade
    skip_installed: true

- name: Enable kernel modules cleanup
  systemd:
    name: linux-modules-cleanup
    enabled: yes

- name: Install archaudit hook
  copy:
    src: arch-audit.hook
    dest: /usr/share/libalpm/hooks
