---
- name: install desktop packages
  pacman:
    name:
      - sway
      - swaybg
      - xorg-server-xwayland
      - waybar
      - mako               # notification daemon
      - kanshi             # autorandr for wayland
      - grim               # screenshots
      - slurp              # region selector
      - wl-clipboard       # clipboard manager
      - brightnessctl      # brightness manager
      - wofi               # rofi for wayland
      - swayidle
      - xdg-user-dirs
    state: present

- name: install video packages
  pacman:
    name:
      - mesa
      - mesa-demos
      - xf86-video-fbdev
    state: present

- name: install audio packages
  pacman:
    name:
      - pulseaudio
      - pulseaudio-alsa
      - pavucontrol
      - pamixer
      - alsa-utils
    state: present

- name: install applications packages
  pacman:
    name:
      - imv                # img visualizer
      - alacritty          # terminal emulator
      - code               # code editor
      - okular             # pdf viewer
      - firefox
      - kolourpaint        # img editor
      - shotwell           # photo manager
      - lxappearance       # theme manager
      - mpv                # video player
      - openvpn
      - rdesktop           # remote desktop client
      - papirus-icon-theme # icon theme
      - youtube-dl
    state: present

- name: add missing gpg keys for aur
  become: no
  shell: gpg --recv --keyserver pool.sks-keyservers.net '{{item}}'
  loop:
    - F4B432D5D67990E3 # wob
  changed_when: false

- name: install aur packages
  become: no
  aur:
    skip_installed: true
    name:
      - equilux-theme
      - wdisplays-git      # arandr for wayland
      - wf-recorder-git    # screen recorder for wayland
      - grimshot-git       # grim+slurp wrapper
      - swaylock-fancy-git # locker for wayland
      - wob                # bars for wayland
      - gnome-ssh-askpass2 # ssh askpass gui
      - downgrade          # package downgrader
      - otf-font-awesome
      - pastel             # color viewer
