---

- name: configure mkinitcpio
  copy:
    src: mkinitcpio.conf
    dest: /etc/
  notify: generates initramfs

- name: configure mkinitcpio preset linux
  copy:
    src: linux.preset
    dest: /etc/mkinitcpio.d/
  notify: generates initramfs
